global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: ingest-api
    metrics_path: /metrics
    static_configs:
      - targets:
          - ingest-api.flycast:8000
        labels:
          service: ingest-api
          env: production

rule_files:
  - alerts.yml
